name: catctr
description: Utility for convenient management of dart and flutter packages
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  console: ^4.1.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  riverpod: ^2.3.7
  yaml_edit: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  json_serializable: ^6.7.1
  lints: ^2.1.1
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1
  test: ^1.24.6

executables:
  catctr: